version: '3'

services:
  web:
    build: ./web/
    image: guiondocker_nginx
    ports:
      - 8080:8080
  app:
    build: ./server/
    image: guiondocker_pyapp
    # デバグ用にポートを開けておく
    ports:
      - 5000:5000
